version: '3'
services:
  # 指定服务名称
  db:
    # 指定服务使用的镜像
    image: mysql:5.7
    # 指定容器名称
    container_name: mysql
    # 指定服务运行的端口
    ports:
      - 3306:3306
    # 指定容器中需要挂载的文件
    volumes:
      - /mydata/mysql/log:/var/log/mysql
      - /mydata/mysql/data:/var/lib/mysql
      - /mydata/mysql/conf:/etc/mysql
    # 指定容器的环境变量
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - linhong_network
  # 指定服务名称
  jackadvanced-docker-compose:
    # 指定服务使用的镜像
    image: jackadvanced/jackadvanced
    # 指定容器名称
    container_name: jackadvanced-docker-compose
    # 指定服务运行的端口
    ports:
      - 8085:8085
    # 指定容器中需要挂载的文件
    volumes:
      - /etc/localtime:/etc/localtime
      - /mydata/app/jackadvanced-docker-compose/logs:/var/logs
    networks:
      - linhong_network

# 指定同一网络
networks:
  linhong_network:
